save_dir: /home/lichong/project/object_detection/output_result/rcnn_s16

class_num: &class_num
  20
input_channels: &input_channels
  3
include_bg: &include_bg
  False
one_stage_model: False
device: '0'
debug: 0
seed: 0


dataset:
  name: voc
  # now only support w == h case
  train_input_size: [416, 512, 608, 736]
  val_input_size: 512
  keep_ratio: True
  image_mean: [0.485, 0.456, 0.406]
  image_std: [0.229, 0.224, 0.225]
  use_difficult: False
  max_bbox_num: 20
  multiscale_interval: 6
  preload_label: False
  num_workers: 0

  train_data_dir:  ['/home/lichong/project/datasets/voc/voc2007/JPEGImages',
                    '/home/lichong/project/datasets/voc/voc2012/JPEGImages']                 
  train_label_dir: ['/home/lichong/project/datasets/voc/voc2007/Annotations',
                    '/home/lichong/project/datasets/voc/voc2012/Annotations']
  train_lst:       ['/home/lichong/project/datasets/voc/voc2007/ImageSets/Main/trainval.txt',
                    '/home/lichong/project/datasets/voc/voc2012/ImageSets/Main/trainval.txt'] 
  val_data_dir:    ['/home/lichong/project/datasets/voc/voc2007/JPEGImages']                 
  val_label_dir:   ['/home/lichong/project/datasets/voc/voc2007/Annotations']
  val_lst:         ['/home/lichong/project/datasets/voc/voc2007/ImageSets/Main/test.txt']
  augmentation:
    flip_h: True
    flip_v: False
    saturation: True
    hue: True
    contrast: True
    crop: False
    gauss: True
    probability: 0.5  
  
train:
  #resume_from: /home/lichong/project/object_detection/checkpoints/fpn_rcnn/checkpoints/checkpoint_epoch_36.pth.tar
  train_batch_size: 2
  val_batch_size: 10
  max_epoch: 42
  lr_decay_epoch: [20, 32]
  lr_decay_scale: 0.1
  log_frequency: 1    # for iter
  first_eval_epoch: 2
  eval_frequency: 2    # for epoch
  metric_iou_thresh: 0.5
  include_bg: False
  freeze_keys: ['layer3', 'layer4']   # notice: if there are keys , then not in the list will be freeze. 
  optimizer:
    #name: Adam
    #lr: 4.0e-4 #0.01
    #amsgrad: True #False
    #weight_decay: 1.0e-4  #0
    name: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  
  loss:
    name: rcnnloss
    rpn_cls_weight: 1.0
    rpn_box_weight: 1.0
    rcnn_cls_weight: 1.0
    rcnn_box_weight: 1.0


network:
  name: faster_rcnn
  backbone:
    name: resnet50
    n_channels: *input_channels
    replace_stride_with_dilation: [False, False, True]
  backbone_resume_from: /home/lichong/project/finetune_models/resnet50-19c8e357.pth
  neck:
    name: fpn
    #multi stages fpn detectcan. value can be int, or list which max length <= 3
    #if len(in_channels) == 1 , means no fpn.
    in_channels: [2048]  
    out_channels: 256
    upsample_mode: nearest
  rpn:
    # anchor_sizes must be [[]] style format, if not fpn , [[128, 256,512]]
    # strides also would be [[]] style format, if not fpn ,[16]
    name: rpn
    in_channels: [256]
    anchor_sizes:  [[128, 256, 512]]
    aspect_ratios: [0.5, 1.0, 2.0]
    strides: [16]
    proposal_min_area: [50]
    proposal_stds: [1, 1, 1, 1] 
    proposal_means: [0, 0, 0, 0]
    rpn_head_type: standard
    rpn_mode_type: sigmoid
    topk_pre_nms_proposals_test: 2000
    topk_post_nms_proposals_test: 300
    nms_thresh: 0.7
    topk_pre_nms_proposals_train: 6000
    topk_post_nms_proposals_train: 2000 
    fg_iou_thresh: 0.7 
    bg_iou_thresh: 0.3                 
    num_sample: 256
    pos_ratio: 0.5
    
  head:
    name: rcnnhead
    proposal_stds: [0.1, 0.1, 0.2, 0.2]
    proposal_means: [0, 0, 0, 0]
    roi_pool_size: 7 
    roi_in_channels: 256
    roi_out_channels: 1024
    num_classes: *class_num
    include_bg: *include_bg
    score_thresh: 0.1
    nms_thresh: 0.5       
    fg_iou_thresh: 0.5
    bg_iou_thresh: 0.5 
    num_sample: 512 
    pos_ratio: 0.25
